# Section 1: Introduction to Jupyter-Notebooks

# Section 2: Introduction to Python

## Printing and Getting Help
Use the **print** command to print variables.

In [ ]:
print('Hello, World!')

With Jupyter notebooks, calling the variable itself acts as a print statement.

In [ ]:
'Hello, World!'

Getting help is easy in Notebooks: append a '?' to the end of a function/variable.

In [ ]:
print?

## Basic Data Types in Python

**NOTE:** Python is an object-oriented language. Every variable in Python is an **instance** (or object) of some type (e.g. integer, list, string) and thus has **attributes.** The following are some useful attributes (i.e. self-contained functions) of lists. Note that all of these attributes modify the variable **in-place**.

### Integers, Floats, and Mathematic Operations
Integers are numbers without a decimal point.

In [ ]:
print(1, type(1))

Floats are numbers with a decimal point.

In [ ]:
print(1.3, type(1.3))

Adding a decimal point will convert an integer to a float.

In [ ]:
print(1., type(1.0))

These are the basic operators in python:

In [ ]:
print(4 + 2)   # Addition
print(4 * 2)   # Multiplication
print(4 / 2)   # Division
print(4 % 2)   # Remainder (modulo)
print(4 ** 2)  # Exponent

Floats dominate integers in operations:

In [ ]:
print(4 + 2.)
print(4 / 2.)
print(4 ** 2.)
print(4 // 2)  # Except for integer division!

Python also supports scientific notation and complex numbers:

In [ ]:
print(1e3)
print(2+3j)

In python, variable assignment is denoted with the equal sign (=). 

In [ ]:
x = 1.

The numeric classes are special in that they allow in-place assignment for convenience. This 

In [ ]:
## In-place addition
x += 1.
print(x)

## In-place multiplcation.
x *= 2.
print(x)

## In-place exponentiation.
x **= 2.
print(x)

### Text and Strings 

Strings are demarcated by single or double quotation marks.

In [ ]:
string = 'a run-of-the-mill string'
string

Paragraphs (e.g. docstrings) can be written with triple quotes:

In [ ]:
paragraph = '''You can use the triple quotes to write paragraphs
of text. Note that any line-break is maintained. Triple quotes are
used to define function docstrings.'''

paragraph

One very useful feature is string substition, where text or numbers can be inserted into a string. String substitution is denoted by the by the percent operator. Different substitutions types exist.  

In [ ]:
# %s: Insert as string (no modification).
print('Hi, my name is %s!' %'Sam')   

# %0._f: Insert a number rounded to the _th digit.
print('Pi to the 2nd digit is %0.2f.' %3.14159) 

# %0._d: Insert a number prepended with _ zeros.
print('Prepend two zeros: %0.3d' %1)

The string object has many associated functions that can be used to modify the string.

In [ ]:
print( 'Original:      %s' %string)
print( 'Capitalize:    %s' %string.capitalize() )
print( 'Uppercase:     %s' %string.upper() )
print( 'Count "i"s:    %s' %string.count('i') ) 
print( 'Replace (i,o): %s' %string.replace('i','o'))

Strings are easily combined, through with the 
addition operator or the join attribute.

In [ ]:
print('This is the first half.' + ' ' + 'This is the second half.')
print(' '.join(['This is the first half.', 'This is the second half.']))

### Booleans
The Boolean objects in Python are the **True** and **False** objects.

In [ ]:
print(True, False) 

In Python, True and False are equvalent to the integers 1 and 0, respectively.

In [ ]:
print(True == 1)   # True is equivalent to 1.
print(False == 0)  # False is equivalent to 0.

These are the comparison operators in python:

In [ ]:
print('4 > 2:  %s' %(4 > 2))    # Greater than
print('4 < 2:  %s' %(4 < 2))    # Less than
print('4 == 2: %s' %(4 == 2))   # Equal to
print('4 >= 2: %s' %(4 >= 2))   # Greater than or equal to
print('4 <= 2: %s' %(4 <= 2))   # Less than or equal to
print('4 != 2: %s' %(4 != 2))   # Not equal to to)

Python also uses **is** and **not** operators.

In [ ]:
print(4 is 2)
print(4 is not 2)

## Containers
### Lists
Lists are the most basic container and are denoted by brackets. Lists can store any pythonic type, and elements of a list do not need to be of the same type.

In [ ]:
example_list = [1, 1., 1e3, 2+3j, True]
print(example_list)

Brackets are used again to index into lists. **NOTE:** Python is a 0-indexed language. The first element of a list 
is the 0th position of the list! 

In [ ]:
print('The first element of the list is %s.' %example_list[0])
print('The third element of the list is %s.' %example_list[2])

Mutliple elements from a list can be retrieved through slicing, which uses the colon operator.

In [ ]:
print(example_list[1:3])    # Second-through-third elements (up-to-not-include)
print(example_list[1:])     # Second element onwards.
print(example_list[:2])     # Up-through-second element.

Slicing also allows for the following operations:

In [ ]:
print('list       = %s' %example_list)

## Second-to-last element onwards
print('list[-2:]  = %s' %example_list[-2:])  

## Up to second-to-last element
print('list[:-2]  = %s' %example_list[:-2])    

## Every other element 
print('list[::2]  = %s' %example_list[::2])

## Reverse elements.
print('list[::-1] = %s' %example_list[::-1]) 

Slicing operators can be combined. Here we extract every other element, starting from the second through the second-to-last.

In [ ]:
print(example_list[1:-1:2])

Indexing and slicing can also be used to update elements in the list.

In [ ]:
example_list[-1] = False
example_list

We can add new elements to the list using **append**. Note that this occurs **in-place.**

In [ ]:
example_list.append( 111 )
example_list

**Insert** allows for adding new elements to specified positions.

In [ ]:
## (Index, Value)
example_list.insert(0, 222)
example_list

Elements can be removed from a list using the **pop** or **remove** function. **Pop** deletes an element by its index, **remove** deletes an element by its value.

In [ ]:
print('Original: %s' %example_list)

## Pop the third element
example_list.pop(2)

## Remove the value 111.
example_list.remove(111)

print('Now: %s' %example_list)

The contents of a list can also be tested with the **in** operator.

In [ ]:
print( 222 in example_list )
print( 999 in example_list )

Strings are essentially lists with characters.

In [ ]:
print('string       = %s' %string)

## 4th character onwards.
print('string[4:]   = %s' %string[4:])   

## Reversed string.
print('string[::-1] = %s' %string[::-1]) 

## Every other character.
print('string[::2]  = %s' %string[::2])

### Tuples
Tuples are denoted by parantheses. Tuples are like lists except that they are **immutable.** Tuples cannot be modified once they are created. 

In [ ]:
example_list = [1, 2, 3, 4]
example_tuple = (1, 2, 3, 4)

In [ ]:
## Change the second element of the list.
example_list[1] = 9
print(example_list)

In [ ]:
## Change the second element of the tuple.
example_tuple[1] = 9
print(example_tuple)

### Dictionaries
Dictionaries are simple lookup tables. They are denoted by curly brackets.

In [ ]:
example_dict = {'a':1, 'b':2, 'c':3}
print(example_dict)
print(example_dict['c'])

Dictionaries can also be generated using the **dict()** command. Notice the slightly different syntax.

In [ ]:
example_dict = dict(a=1, b=2, c=3)
print(example_dict)
print(example_dict['c'])

Dictionaries are comprised of "keys" and "values".

In [ ]:
print(example_dict.keys())
print(example_dict.values())

Once initialized, new key/value pairs can be stored in a dictionary.

In [ ]:
example_dict['d'] = 4
print(example_dict)

## Control Flow in Python

### For and While Loops
For loops have a very simple syntax. 

In [ ]:
for x in [0, 1, 2, 3, 4]:
    print(x)

Elements of a list can be directly iterated over in python.

In [ ]:
for x in ['how', 'now', 'brown', 'cow']:
    print(x)

For loops can be paired with the **enumerate** command for indexing.

In [ ]:
for i, x in enumerate(example_list):
    print(i,x)

The **zip** command can be used to iterate over multiple lists at once.

In [ ]:
list1 = [0, 2, 4, 6, 8]
list2 = ['zero', 'two', 'four', 'six', 'eight']

for a,b in zip(list1,list2):
    print(a,b)

**While** loops are similarly simple. While loops are initialized with a boolean statement. While True, the while loop will continue executing. Once False, the while loop terminates.

In [ ]:
i = 0
while i < 5:
    print(i)
    i += 1  

### Conditional logic with if, elif, else

In python, the three conditional statements are if, elif, and else.
Here we will construct a simple for-loop testing parity.

In [ ]:
example_list = [4, 7, 9.4]

for x in example_list:
    
    if x % 2 == 0: 
        print('%s is even.' %x)
        
    elif x % 2 == 1:
        print('%s is odd.' %x)
        
    else: 
        print('%s is not an integer.' %x)

### Contiue and Break statements
Conditional logic statements can be paired with the "continue" and "break" 
statments for additional control flow in For and While loops. The "continue"
statement skips the current iteration of a For/While loop, whereas the
"break" statement terminates the For/While loop.

Below is an example of the continue statement. The for loop skips at the odd numbers.

In [ ]:
example_list = [4, 7, 9.4]

for x in example_list:
    
    if x % 2 == 0: 
        print('%s is even.' %x)
        
    elif x % 2 == 1:
        continue
        print('%s is odd.' %x)
        
    else: 
        print('%s is not an integer.' %x)

An example of the **break** statement. The for loop terminates at the first odd number.

In [ ]:
example_list = [4, 7, 9.4]

for x in example_list:
    
    if x % 2 == 0: 
        print('%s is even.' %x)
        
    elif x % 2 == 1:
        break
        print('%s is odd.' %x)
        
    else: 
        print('%s is not an integer.' %x)

### List comprehensions
Python also allows for embedding For loops within lists as a nifty way of constructing/modifying lists. List comprehensions are very powerful (though sometimes memory intensive) and can be constructed with a few different syntaxes.

Inclusive/exclusive list comprehension: here we exclude variables from the list if they do not meet a certain criterion.

In [ ]:
[x for x in range(10) if x > 5]

Conditional list comprehension: here we transform variables from the list based on whether they meet a certain criterion.

In [ ]:
['odd' if x % 2 == 1 else 'even' for x in range(5)]

Note that else statements can be chained in list comprehensions.

In [ ]:
example_list = [4, 7, 9.4]

['odd' if x % 2 == 1 else 'even' if x % 2 == 0 else 'non-integer' for x in example_list]

### Error handling with try/except logic.
Python allows for intelligent error handling with the "try" and "except" logics. Code nested under a "try" command will be evaluated. If an error arises under a try block, the code in the except block will be evaluated instead. This is useful for handling exceptions and preventing scripts from breaking. Use with caution though if you cannot predict error corner cases!

Here we will test try/except logic with a division-by-zero error. Note that I am specifying the error class, i.e. ZeroDivisionError. Python has a number of built-in error types, and it is better to specify the exact type of error you expect to ensure that only those types of errors are passed to the except block. Multiple excepts are permissible in try/except workflows.

In [ ]:
## An example divide by zero error.
example_list = [2, 10, 0]

for x in example_list:
    print(20 / x)

In [ ]:
## An example try/catch handling divide by zero errors.
example_list = [2, 10, 0]

for x in example_list:
    try:
        print(20 / x)
    except ZeroDivisionError: 
        print('You cannot divide 0, silly!')

## Basic Commands in Python

The most important command is the **range** command. Range produces a list of sequential integers and is identical to **seq** in R.

In [ ]:
print('range(5)     = %s' %range(5))     # Specify stop position.
print('range(0,5)   = %s' %range(5))     # Specify start & stop position
print('range(0,5,2) = %s' %range(0,5,2)) # Specify start, stop, and by.

for x in range(0,5,2):
    print(x)

Each python type has its own function for the purpose of converting variables to different types. 

In [ ]:
X = range(5)

print( list(X) )    # Range as list.
print( tuple(X) )   # Range as tuple.
print( str(X) )     # Range as string (converts to string literally).

The **type** and **isinstance** commands can be used to check the type of variables.

In [ ]:
X = [1, 4, 5, 2]

print( type(X) )
print( type(X) == str )
print( isinstance(X, list) )

In [ ]:
## There are commands to modify lists

In [ ]:
example_list = [4, 1, 5, 2, 7, 1, 2, 3]

print(sorted(example_list))    # Sort list.
print(set(example_list))       # Get unique elements of list. Returns set.

In [ ]:
## There are also commands to summarize lists.
print(len(example_list))    # Count element in list.
print(sum(example_list))    # Sum across list.

In [ ]:
## The any/all commands are very useful for testing if any 
## conditionals are met in a list.
example_list = [True if x > 2 else False for x in range(5)]
print(example_list)
print(any(example_list))
print(all(example_list))

## Defining Functions
Define new functions with **def** and **return** functions. Any arguments specified in the **def** statement are necessary arguments for the newly defined function. 

In [ ]:
def average(X):
    '''Compute arithmetic mean for list, X.'''
    return sum(X) / len(X)

average?

In [ ]:
## Define an example list.
example_list = [2, 2, 2, 3, 3, 2, 1, 4]

## Compute average.
print( 'Average: %0.3f' %average(example_list) )

Arguments of user-defined functions can also be assigned default parameters.

In [ ]:
def average(X, weights=False):
    '''Compute arithmetic mean for list, X. Weighted average will be computed if weights are given.'''
    if not weights: weights = [1] * len(X)
    return sum( [x*w for x,w in zip(X,weights)] ) / sum(weights)    

## Define some weights.
weights = [1, 1, 1, 0.5, 0.5, 2, 4, 0.25]

## Compute average / weighted average.
print( 'Average:          %0.3f' %average(example_list) )
print( 'Weighted average: %0.3f' %average(example_list, weights) )

In [ ]:
## The lambda operator can also be used to define short functions.
average = lambda X: sum(X) / len(X)

print( 'Average: %0.3f' %average(example_list) )

# Section 3: Introduction to Numpy

## Importing Modules
If vanilla python seems rather lackluster, that's because it is. Fortunately, the scientific stack adds a broad and powerful array of python packages fill in the gaps. Once installed, packages in python are easily loaded for use.

In [1]:
import numpy
print(numpy.__version__)

1.13.0


Commands from packages are like attributes of objects. For convenience, we will import packages using shorthand.

In [2]:
import numpy as np
print(np.__version__)

1.13.0


## NumPy Arrays
### Why arrays improve on lists
Arrays are the most basic type of the NumPy package. NumPy arrays are vectors (Nx1), similar to pythonic lists. In contrast to lists, however, arrays have many more attributes and can be modified in substantially more ways. Several examples are provided below demonstrating the improvement of arrays over lists.

In [8]:
## Define example list.
example_list = list(range(5))

print(example_list)
print(example_list * 3)            # scalar * list
print(example_list * example_list) # list * list

[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]


TypeError: can't multiply sequence by non-int of type 'list'

In contrast, NumPy arrays can be modified in this way. We use the **arange** command to initialize an array of sequential integers.

In [ ]:
arr = np.arange(5)

print(arr)
print(arr * 3)
print(arr * arr)

Every array has an object type. These can be looked up and modified.

In [12]:
print(arr, arr.dtype)   # Print current datatype.
arr = arr.astype(float) # Conver to float.
print(arr, arr.dtype)   # Print new datatype.

[0 1 2 3 4] int64
[ 0.  1.  2.  3.  4.] float64


Numpy arrays store metadata about their contents. These can be helpful, especially the **shape** atribute.

In [16]:
print('Array shape:', example_array.shape) # Print shape of array.
print('Array size:', example_array.nbytes) # Print bytes of array.

Array shape: (5,)
Array size: 40


Arrays now have a number of other built-in attributes 
not available for lists.

In [ ]:
print(example_array.min())     # Get max of array.
print(example_array.max())     # Get min of array.
print(example_array.mean())    # Get mean of array.
print(example_array.sum())     # Get sum of array.

### Generating NumPy Arrays
There are many ways of generating NumPy arrays. The most simple way is to convert a Python list to NumPy array using the **array** command.

In [20]:
## Making an array from a list using the array command.
example_list = [4, 7, 9.4]
arr = np.array(example_list)

print(example_list)
print(arr) 

[4, 7, 9.4]
[ 4.   7.   9.4]


NumPy has recreated all of the standard R/Matlab commands for 
generating arrays.

In [46]:
print('np.arange(5)        = %s' %np.arange(5))         # Array of 5 sequential integers.
print('np.zeros(5)         = %s' %np.zeros(5))          # Array of 5 zeros.
print('np.ones(5)          = %s' %np.ones(5))           # Array of 5 ones.
print('np.empty(5)         = %s' %np.empty(5))          # Array of 5 "empty" values.
print('np.linspace(0,10,5) = %s' %np.linspace(0,10,5))  # Length-5 evenly-spaced array from 0 to 10.

np.arange(5)        = [0 1 2 3 4]
np.zeros(5)         = [ 0.  0.  0.  0.  0.]
np.ones(5)          = [ 1.  1.  1.  1.  1.]
np.empty(5)         = [ 1.  1.  1.  1.  1.]
np.linspace(0,10,5) = [  0.    2.5   5.    7.5  10. ]


## NumPy Matrices
### Why matrices improve on lists
It is possible to represent matrices in pythonic lists, though it is inefficient. Similar to the benefits of arrays, NumPy matrices dramatically improve upon the numerical capabilities of core python. Python can technically represent matrices as a list of lists.

In [53]:
nested_lists = [[1,2,3,4],
                [4,5,6,7]]

print(nested_lists)
print(nested_lists[1][2])   # To extract the 2nd row, 3rd column, two brackets are necessary.

[[1, 2, 3, 4], [4, 5, 6, 7]]
6


NumPy matrices make this much easier!

In [54]:
mat = np.array(nested_lists)

print(mat)
print(mat[1,2])    # Much more efficient indexing!

[[1 2 3 4]
 [4 5 6 7]]
6


Indexing of NumPy matrices (and arrays for that matter) obey all of the slicing conventions of lists. Commas are used to demarcate which axis a slice operation is targeting.

In [57]:
print('mat[1,2]  = %s' %mat[1,2])    # Second row, third column.
print('mat[0,:]  = %s' %mat[0,:])    # All the first row.
print('mat[:,-1] = %s' %mat[:,-1])   # All of the final column.

mat[1,2]  = 6
mat[0,:]  = [1 2 3 4]
mat[:,-1] = [4 7]


NumPy matrices have all the same attributes of NumPy arrays, but now functions can be applied to specific rows or columns in addition to the entire matrix.

In [58]:
print( mat.sum() )          # Sum across matrix.
print( mat.sum(axis=0) )    # Sum across columns.
print( mat.sum(axis=1) )    # Sum across rows.

32
[ 5  7  9 11]
[10 22]


Note that arrays and matrices, despite different sizes, are the actually same NumPy class under the hood.

In [60]:
print(type(arr))
print(type(mat))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### Generating NumPy Matrices

In [ ]:
## As demonstrated above, a nested list-of-lists can be made
## into a NumPy matrix.
example_list = [[0, 1, 1],[2, 3, 5], [8, 13, 21]]
example_matrix = np.array(example_list)

print(example_list)
print(example_matrix)

In [ ]:
## Matrices can also be formed by joining arrays using hstack, vstack, or concatenate.
## hstack joins column vectors, vstack joins row vectors, and concatenate
## allows the user to specify which axis to merge across.

example_array = np.arange(4).reshape(4,1)
print( np.hstack( [example_array,example_array] ) )    # Stack two arrays horizontally.

example_array = example_array.reshape(1,4)
print( np.vstack( [example_array,example_array] ) )    # Stack two arrays vertically.

print( np.concatenate( [example_array, example_array], axis=0 ))

In [ ]:
## NumPy has recreated all of the standard R/Matlab commands for 
## generating matrices.
print( np.zeros( [3,3] ) )                 # 3x3 matrix of zeros.
print( np.ones( [3,3] ) )                  # 3x3 matrix of ones.
print( np.arange(9).reshape(3,3) )         # 3x3 matrix of sequential integers.
print( np.linspace(0,8,9).reshape(3,3) )   # 3x3 matrix evenly-spaced array from 0 to 8. 
print( np.identity(3) )                    # 3x3 identity matrix.

In [ ]:
## Importantly, reshape can be used to change the shape of 
## NumPy arrays. The order flag can also change how they are
## organized (row-ordered vs. column-ordered).
example_array = np.arange(8)
print(example_array)
print(example_array.reshape(2,4,order='C'))    # Column-organized (default)
print(example_array.reshape(2,4,order='F'))    # Row-organized

In [ ]:
## The flatten command can be used to flatten matrices to arrays.
example_matrix = np.identity(3)
print(example_matrix)
print(example_matrix.flatten())

## Core NumPy Functions
NumPy also introduces a number of useful functions designed to operate efficiently over NumPy arrays. The following is a non-exhaustive overview of some important NumPy functions.

### Rounding Functions

In [ ]:
## NumPy has the same rounding functions as R.
example_array = np.linspace(0,1,4)
print(example_array)
print( np.round(example_array, 2) )    # Round to the 2nd decimal.
print( np.floor(example_array) )       # Round down.
print( np.ceil(example_array) )        # Round up.

### Mathematical functions

In [ ]:
## NumPy includes a variety of mathematical functions.
## All of these can be applied across an entire matrix 
## or across arrays.

np.sum;       # Sum of an array or matrix.
np.cumsum;    # Cumulative sum over an array.
np.prod;      # Product of elements of an array.
np.divide;    # Element-wise division of two arrays.
np.diff;      # Pairwise difference of elements of an array.
np.exp;       # Exponential transform.
np.log;       # Natural logarithm.
np.log10;     # Base-10 logarithm.

### Summary Functions

In [ ]:
## NumPy includes many functions to summarize an array.
## With the exception of correlate, all of these can be
## applied across an entire matrix or across arrays.

np.min;           # Return the smallest element.
np.max;           # Return the largest element.
np.argmin;        # Return the index of the smallest element.
np.argmax;        # Return the index of the largest element.
np.mean;          # Compute the mean of an array.
np.std;           # Compute the standard deviation of an array.
np.var;           # Compute the variance (sd^2) of an array.
np.percentile;    # Compute the xth percentile of an array.
np.corrcoef;      # Compute the row-/col-wise correlation of a matrix.

### Set Functions

In [ ]:
## NumPy includes functions for identifying unique elements
## within or between arrays.
arr1 = np.array([41, 16, 34, 0, 2, 20, 19, 14, 22, 15, 18, 9, 35, 41])
arr2 = np.array([42, 22, 40, 7, 33, 0, 12, 19, 44, 10, 31, 11, 11, 49])

In [ ]:
# Sort elements (ascending order).
np.sort(arr1)

In [ ]:
# Return unique elements.
np.unique(arr1)

In [ ]:
# Return unique elements, count number of appearances.
np.unique(arr1, return_counts=True)

In [ ]:
# Find the elements of array-1 in array-2.
np.in1d(arr1, arr2)

In [ ]:
# Return all unique elements of arrays 1 & 2.
np.union1d(arr1, arr2)

In [ ]:
# Return all elements belonging to both arrays 1 & 2.
np.intersect1d(arr1, arr2)

### Shortcut Functions

In [ ]:
## NumPy includes a number of very helpful functions that act to replace list 
## comprehensions (np.where) and for loops (np.apply_across_axis, np.apply_over_axes). 
## These are often more efficient than writing out a full For loop.
## We will emphasize these functions with a simple example of standard-scoring (z-scoring)
## a matrix.

## Define the standard score (z-score) function.
def zscore(arr): 
    '''Standard score'''
    return (arr - arr.mean()) / arr.std()

## Define a simple matrix.
mat = np.arange(12).reshape(2,6)
print(mat)

## Use np.appy_across_axis to apply our function across each row.
zmat = np.apply_along_axis(zscore, axis=1, arr=mat)
print(zmat.round(2))

## Use the np.where command to set all negative numbers to 0, else 1.
## np.where is identical to the which() command in R. 
amat = np.where(zmat < 0, 0, 1)
print(amat)

## If no transforms are specified, np.where returns the indices of the
## array where the conditional is met.
print( np.where(zmat < 0 ) )

### Linear Algebra Functions

In [ ]:
## NumPy includes an entire submodule dedicated to efficient linear 
## algebra functions (though it should be noted that SciPy has
## reimplemented them for maximal efficiency). See np.linalg for 
## a full list of commands.
mat = np.arange(16).reshape(4,4)

print(mat)
print(mat.T)           # Transpose the matrix
print(np.diag(mat))    # Return diagonal of matrix
print(np.triu(mat))    # Return upper triangular matrix
print(mat.dot(mat))    # Matrix multiply itself.

In [ ]:
## Linear algebra operations include:
np.linalg.norm;        # Vector or matrix norm
np.linalg.inv;         # Inverse of a square matrix
np.linalg.det;         # Determinant of a square matrix
np.linalg.eig;         # Eigenvalues and vectors of a square matrix
np.linalg.cholesky;    # Cholesky decomposition of a matrix
np.linalg.svd;         # Singular value decomposition of a matrix
np.linalg.lstsq;       # Solve linear least-squares problem

### Generating Random Data

In [ ]:
## NumPy also includes many functions for generating random data. 
## For a full list of functions, tab-complete on np.random.

print( np.random.randint(0,10,10) )    # Generate ten random integers between 0-9.
print( np.random.normal(0,1,5) )       # Generate five random samples of a normal distribution with mu=0,sd=1.
print( np.random.binomial(1,0.5,10))   # Generate 10 random coin flips.

print( np.random.choice(np.arange(10), 5, replace=False) ) # Choose five numbers from 0-9 without replacement.