# Core Python Exercises

## Exercise 1
The goal of this exercise is to get used to making and manipulating lists. The elements of the to-be list are: 

In [ ]:
3 'Yankee' 7.6 None False 2.5e-2 'Foxtrot'

### Store the elements above in a new list.

In [1]:
new_list = [3, 'Yankee', 7.6, None, False, 2.5e-2, 'Foxtrot']

### Return the 3rd element of the list.

In [2]:
print(new_list[2])

7.6


### Return the 2nd-to-last element of the list.

In [3]:
print(new_list[-2])

0.025


### Return every third element, starting from the 2nd element.

In [4]:
print(new_list[1::3])

['Yankee', False]


### Using the "type" command, print the type of each element of the list.
Hint: Use a for loop to make this less tedious.

In [5]:
for elem in new_list:
    print(type(elem))

<class 'int'>
<class 'str'>
<class 'float'>
<class 'NoneType'>
<class 'bool'>
<class 'float'>
<class 'str'>


### With a For loop, store each element and its type as a key and value, respectively, in a dictionary. 

In [6]:
lookup = dict()
for elem in new_list:
    lookup[elem] = type(elem)
print(lookup)

{3: <class 'int'>, 'Yankee': <class 'str'>, 7.6: <class 'float'>, None: <class 'NoneType'>, False: <class 'bool'>, 0.025: <class 'float'>, 'Foxtrot': <class 'str'>}


## Exercise 2
Complete the exercises below with the following quote: 
>“It's the sides of the mountain which sustain life, not the top.”

### Return the fifth character of the sentence.

In [7]:
new_string = "It's the sides of the mountain which sustain life, not the top."
print(new_string[5])

t


### Return the substring *"of the mountain"* from the sentence.
Hint: Lookup the "index" string attribute.

In [8]:
i = new_string.index('of')
j = new_string.index('which')
print(new_string[i:j])

of the mountain 


### Using the **count** attribute, find if there are more *i*'s or *e*'s in this sentence.
Hint: Careful with capitalization. Use the **lower** attribute.

In [9]:
print(new_string.lower().count('i'))
print(new_string.lower().count('e'))

6
5


### Reverse the order of the words of the sentence, without reversing the characters.
Hint: You will need to use the split and join attributes.

In [10]:
words = new_string.split(' ')
words = words[::-1]
new_string = ' '.join(words)
print(new_string)

top. the not life, sustain which mountain the of sides the It's


## Exercise 3
Find the intersection of the following two lists using only list comprehensions.

In [11]:
list1 = [41, 16, 34, 0, 2, 20, 19, 14, 22, 15, 18, 9, 35, 41]
list2 = [42, 22, 40, 7, 33, 0, 12, 19, 44, 10, 31, 11, 11, 49]
print([elem for elem in list1 if elem in list2])

[0, 19, 22]


## Exercise 4
Starting with the list below, construct a **While loop** that returns the [Fibonacci numbers](https://en.wikipedia.org/wiki/Fibonacci_number) and terminates only when the most recent number is greater than 5000.

In [12]:
numbers = [0,1]
while numbers[-1] < 5000:
    numbers.append( numbers[-2] + numbers[-1] )
print(numbers)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765]


## Exercise 5
Define a function that checks if an inputted integer is prime. Test your function on the following numbers: 
>1411, 1147, 2327, 2683, 33233

Only one number above is not prime. As a challenge, if the tested integer is not prime, have the function return a number the integer is divisible by.

In [13]:
## Solution 1

def is_prime(i):
    divisors = range(2,i)
    remainders = [True if i % d == 0 else False for d in divisors]
    if any(remainders):
        print('%s is divisible by %s.' %(i,divisors[remainders.index(True)]))
    else:
        print('%s is prime!' %i)

for i in [1411, 1147, 2327, 2683, 33233]:
    is_prime(i)

1411 is divisible by 17.
1147 is divisible by 31.
2327 is divisible by 13.
2683 is prime!
33233 is divisible by 167.


In [14]:
## Solution 2

def is_prime(i):
    d = 2
    while d < i:
        if i % d == 0:
            return(d)
        else:
            d += 1
    
    return(None)

for i in [1411, 1147, 2327, 2683, 33233]:
    print('%s is divisible by %s.' %(i,is_prime(i)))

1411 is divisible by 17.
1147 is divisible by 31.
2327 is divisible by 13.
2683 is divisible by None.
33233 is divisible by 167.


# NumPy Exercises

## Exercise 1
### Generate an array of numbers 0-24. Reshape to a 5x5 matrix.

In [15]:
import numpy as np
mat = np.arange(25).reshape(5,5)
print(mat)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### Extract the diagonal of this matrix.

In [16]:
diag = np.diag(mat)
print(diag)

[ 0  6 12 18 24]


### Multiply the matrix by an identity matrix of the same shape. Confirm that it is identical to the original.
Hint: Use **np.all** command to confirm all equal. 

In [17]:
imat = np.identity(5)
new_mat = mat.dot(imat)
print( np.all(mat == new_mat) )

True


### Using *np.concatenate*, join the matrix with itself and return a new matrix with shape (5,5,2).
Hint: Use reshape to give the matrix a third axis before using using **np.concatenate**.

In [18]:
new_mat = np.concatenate([mat.reshape(5,5,1), mat.reshape(5,5,1)], axis=-1)
print(new_mat.shape)

(5, 5, 2)


### Compute the mean of the concatenated matrix along the third axis. Confirm its equal to the original matrix.

In [19]:
new_mat = new_mat.mean(axis=-1)
print( np.all(mat == new_mat) )

True


### Return the indices of the matrix where the elements are greater than 15.

In [20]:
print( np.where(mat > 15) )

(array([3, 3, 3, 3, 4, 4, 4, 4, 4]), array([1, 2, 3, 4, 0, 1, 2, 3, 4]))


### Using *np.where*, set all elements of the matrix greater than 15 to 1, else 0.


In [21]:
print( np.where(mat > 15, 1, 0) )

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 1 1 1]
 [1 1 1 1 1]]


### Set all elements of the matrix greater than 15 to 2, less than 5 to 1, else 0.
Hint: **np.where** can be passed as an input to **np.where**.

In [22]:
print( np.where( mat > 15, 2, np.where(mat < 5, 1, 0) ) )

[[1 1 1 1 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 2 2 2 2]
 [2 2 2 2 2]]


### Return the lower triangular matrix.

In [23]:
print( np.tril(mat) )

[[ 0  0  0  0  0]
 [ 5  6  0  0  0]
 [10 11 12  0  0]
 [15 16 17 18  0]
 [20 21 22 23 24]]


### Define a demean function.

In [24]:
def demean(arr):
    return arr - arr.mean()

### Apply the demean function across each row of the matrix.

In [25]:
print( np.apply_along_axis(demean, 1, mat) )

[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]


## Exercise 2
In this exercise, we will demonstrate the 68–95–99.7 rule of normal distributions. 
### Simulate 100 data points from a normal distribution with: 
> mu = 0

>sd = 0.5.

In [26]:
data = np.random.normal(0,0.5,500)

### Compute the mean and standard deviation of your sample.

In [27]:
mu = np.mean(data)
sd = np.std(data)
print(mu,sd)

-0.00955899690831 0.495423475293


### Find the fraction of data within (mu - 1sd, mu + 1sd)
Hint: Use the chaining of np.where

In [28]:
within_1sd = np.where( data < mu - sd, 0, np.where( data > mu + sd, 0, 1) )
print( np.mean(within_1sd) )

0.672


### Find the fraction of data within (mu - 2sd, mu + 2sd)

In [29]:
within_1sd = np.where( data < mu - 2*sd, 0, np.where( data > mu + 2*sd, 0, 1) )
print( np.mean(within_1sd) )

0.956


### Find the fraction of data within (mu - 3sd, mu + 3sd)

In [30]:
within_1sd = np.where( data < mu - 3*sd, 0, np.where( data > mu + 3*sd, 0, 1) )
print( np.mean(within_1sd) )

1.0


## Exercise 3

### Using *np.random.multivariate_normal*, simulate 100 observations of two variables drawn from a multivariate normal with parameters:
> mu = [0,0]

> cov = [1.0, 0.4]<br>
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[0.4, 1.0]

In [31]:
mu = np.array([0,0])
cov = np.array([[1,0.4],[0.4,1.0]])
data = np.random.multivariate_normal(mu,cov,100)

### Correlate the variables.
Hint: Remember the transposition attribute.

In [32]:
print( np.corrcoef(data.T) )

[[ 1.          0.43025912]
 [ 0.43025912  1.        ]]


### Perform linear regression using *np.linalg.lstsq*.

In [33]:
x = data[:,0].reshape(100,1)
y = data[:,1]
beta, _, _, _ = np.linalg.lstsq(x,y)

print(beta)

[ 0.42991788]
